[package]
name = "bashpic"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = "0.5.0"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
tokio = { version = "1", features = ["full"] }
